apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-n8og
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0001-tenant/tkrw-pr712-0075-0001-app/devfile-sample-n8og@sha256:f0482cf8f083e5f051177134f1d911ff0f70fe10df79a89436b45030f4b59012
        name: my-nodejs
        resources: {}
status: {}
